### ISSUE TITLE
Fatal error: Interface 'Zend\Module\Consumer\AutoloaderProvider' not found in vendor\zf-commons\ZfcFacebook\Module.php on line 11

### ISSUE THREAD

**Issue by ghost** [ZF-Commons/ZfcFacebook#2]
Fatal error: Interface 'Zend\Module\Consumer\AutoloaderProvider' not found in vendor\zf-commons\ZfcFacebook\Module.php on line 11

**Comment by GeeH** [comment]
Hi,

Can you update and make sure you are on ZF2 beta5, and give me some example code please?

G

**Comment by ghost** [comment]
Hi,
What's the package to update?
ZF-Commons / ZfcFacebook  or Spabby / ZfcFacebook ?

**Comment by GeeH** [comment]
I'm working on it now, feel free to pop into IRC if you want to chat, it's not beta5 compliant as it is, expect working example later today :).

**Comment by ghost** [comment]
ok no problem ;-)

**Comment by GeeH** [comment]
I've submitted a PR, but no idea how to make changes from my fork overwrite what's in the origin repo :D should get fixed at some point today when I can grab another zfc-commons person to merge changes.
