### ISSUE TITLE
Fatal error: Class ZfcFacebook\Module contains 1 abstract method and must therefore be declared abstract or implement the remaining methods 

### ISSUE THREAD

**Issue by ghost** [ZF-Commons/ZfcFacebook#5]
Fatal error: Class ZfcFacebook\Module contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend\ModuleManager\Feature\ServiceProviderInterface::getServiceConfig) in vendor\zf-commons\ZfcFacebook\Module.php on line 74

**Comment by GeeH** [comment]
Need to merge a PR sorry, will do this afternoon.
